### ISSUE TITLE
Adding new spectrum data for [Italy]

### ISSUE THREAD

**Issue by MattiaFenzi** [davwheat/mobile-spectrum-data#32]
### Country name (English)

Italy

### Country name (native language)

Italia

### Country two-letter code

IT

### JSON spectrum data file

[
  {
    "names": [
      "B1, n1"
    ],
    "spectrumData": [
      {
        "earfcns": [
          125
        ],
        "endFreq": 2130,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "pairedWith": {
          "endFreq": 1940,
          "startFreq": 1920,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2110,
        "type": "fddDown",
        "uarfcns": [
          10563
        ]
      },
      {
        "details": [
          "EARFCN 275 is used for 10 or 15 MHz of LTE",
          "EARFCN 300 is used for 10 MHz of LTE"
        ],
        "earfcns": [
          275,
          300
        ],
        "endFreq": 2145,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 1955,
          "startFreq": 1940,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2130,
        "type": "fddDown"
      },
      {
        "earfcns": [
          400
        ],
        "endFreq": 2155,
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "pairedWith": {
          "endFreq": 1965,
          "startFreq": 1955,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2145,
        "type": "fddDown"
      },
      {
        "details": [
          "5G NR operating as DSS n1"
        ],
        "earfcns": [
          525
        ],
        "endFreq": 2170,
        "nrarfcns": [
          432050,
          433010
        ],
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 1980,
          "startFreq": 1965,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2155,
        "type": "fddDown"
      }
    ]
  },
  {
    "names": [
      "B3, n3"
    ],
    "spectrumData": [
      {
        "earfcns": [
          1225
        ],
        "endFreq": 1810,
        "owner": "Public Safety",
        "ownerLongName": "Public Safety",
        "pairedWith": {
          "endFreq": 1715,
          "startFreq": 1710,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1805,
        "type": "fddDown"
      },
      {
        "details": [
          "5G NR is operating as DSS n3 in some trial sites",
          "Rarely used for DCS"
        ],
        "earfcns": [
          1350
        ],
        "endFreq": 1830,
        "nrarfcns": [
          365530
        ],
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 1735,
          "startFreq": 1715,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1810,
        "type": "fddDown"
      },
      {
        "earfcns": [
          1500
        ],
        "endFreq": 1840,
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "pairedWith": {
          "endFreq": 1745,
          "startFreq": 1735,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1830,
        "type": "fddDown"
      },
      {
        "details": [
          "5G NR operating as DSS n3",
          "Rarely used for DCS"
        ],
        "earfcns": [
          1650
        ],
        "endFreq": 1860,
        "nrarfcns": [
          368890,
          371530
        ],
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "pairedWith": {
          "endFreq": 1765,
          "startFreq": 1745,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1840,
        "type": "fddDown"
      },
      {
        "details": [
          "Rarely used for DCS"
        ],
        "earfcns": [
          1850
        ],
        "endFreq": 1880,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 1785,
          "startFreq": 1765,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1860,
        "type": "fddDown"
      }
    ]
  },
  {
    "names": [
      "B7, n7"
    ],
    "spectrumData": [
      {
        "details": [
          "From September 2020 to March 2022 this block was used by Iliad in some regions"
        ],
        "earfcns": [
          2800
        ],
        "endFreq": 2630,
        "owner": "Public Safety",
        "ownerLongName": "Public Safety",
        "pairedWith": {
          "endFreq": 2510,
          "startFreq": 2500,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2620,
        "type": "fddDown"
      },
      {
        "earfcns": [
          2900
        ],
        "endFreq": 2640,
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "pairedWith": {
          "endFreq": 2520,
          "startFreq": 2510,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2630,
        "type": "fddDown"
      },
      {
        "earfcns": [
          3025
        ],
        "endFreq": 2655,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 2535,
          "startFreq": 2520,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2640,
        "type": "fddDown"
      },
      {
        "earfcns": [
          3175
        ],
        "endFreq": 2670,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 2550,
          "startFreq": 2535,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2655,
        "type": "fddDown"
      },
      {
        "details": [
          "5G NR operating as DSS n7 when DCS is deployed"
        ],
        "earfcns": [
          3350
        ],
        "endFreq": 2690,
        "nrarfcns": [
          535010,
          537410
        ],
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "pairedWith": {
          "endFreq": 2570,
          "startFreq": 2550,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2670,
        "type": "fddDown"
      }
    ]
  },
  {
    "names": [
      "B8"
    ],
    "spectrumData": [
      {
        "endFreq": 930.1,
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "pairedWith": {
          "endFreq": 885.1,
          "startFreq": 880.1,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 925.1,
        "type": "fddDown",
        "uarfcns": [
          2938
        ]
      },
      {
        "arfcns": [
          "1-25",
          "1000-1023"
        ],
        "details": [
          "LTE is operating only on some trial sites"
        ],
        "earfcns": [
          3526
        ],
        "endFreq": 940,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 895,
          "startFreq": 885.2,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 930.2,
        "type": "fddDown"
      },
      {
        "arfcns": [
          "27-75"
        ],
        "details": [
          "LTE is operating only on some trial sites"
        ],
        "earfcns": [
          3676
        ],
        "endFreq": 950,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 905,
          "startFreq": 895.4,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 940.4,
        "type": "fddDown"
      },
      {
        "arfcns": [
          "77-124"
        ],
        "endFreq": 959.8,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "pairedWith": {
          "endFreq": 914.8,
          "startFreq": 905.2,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 950.2,
        "type": "fddDown",
        "uarfcns": [
          3063
        ]
      }
    ]
  },
  {
    "names": [
      "B20"
    ],
    "spectrumData": [
      {
        "earfcns": [
          6200
        ],
        "endFreq": 801,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "pairedWith": {
          "endFreq": 842,
          "startFreq": 832,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 791,
        "type": "fddDown"
      },
      {
        "earfcns": [
          6300
        ],
        "endFreq": 811,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 852,
          "startFreq": 842,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 801,
        "type": "fddDown"
      },
      {
        "earfcns": [
          6400
        ],
        "endFreq": 821,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 862,
          "startFreq": 852,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 811,
        "type": "fddDown"
      }
    ]
  },
  {
    "names": [
      "B28, n28"
    ],
    "spectrumData": [
      {
        "details": [
          "5G NR operating as DSS n28"
        ],
        "earfcns": [
          9260
        ],
        "endFreq": 768,
        "nrarfcns": [
          152690
        ],
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "pairedWith": {
          "endFreq": 713,
          "startFreq": 703,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 758,
        "type": "fddDown"
      },
      {
        "details": [
          "Still no deploy of 700 MHz (except for some trial sites), unsure if is DSS or NR only, NRARFCN unknown"
        ],
        "earfcns": [
          9360
        ],
        "endFreq": 778,
        "nrarfcns": [
          "unknown"
        ],
        "owner": "Tim",
        "ownerLongName": "Tim",
        "pairedWith": {
          "endFreq": 723,
          "startFreq": 713,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 768,
        "type": "fddDown"
      },
      {
        "details": [
          "Started as LTE only, some sites have enabled 5G NR operating as DSS n28"
        ],
        "earfcns": [
          9460
        ],
        "endFreq": 788,
        "nrarfcns": [
          156510
        ],
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "pairedWith": {
          "endFreq": 733,
          "startFreq": 723,
          "type": "fddUp"
        },
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 778,
        "type": "fddDown"
      }
    ]
  },
  {
    "names": [
      "B32"
    ],
    "spectrumData": [
      {
        "earfcns": [
          10020
        ],
        "endFreq": 1472,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1452,
        "type": "sdl"
      },
      {
        "earfcns": [
          10220
        ],
        "endFreq": 1492,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 1472,
        "type": "sdl"
      }
    ]
  },
  {
    "names": [
      "B38"
    ],
    "spectrumData": [
      {
        "details": [
          "Unused TDD spectrum"
        ],
        "endFreq": 2575,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2570,
        "type": "tdd"
      },
      {
        "earfcns": [
          37900
        ],
        "endFreq": 2595,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2575,
        "type": "tdd"
      },
      {
        "details": [
          "Unused TDD spectrum"
        ],
        "endFreq": 2600,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2595,
        "type": "tdd"
      },
      {
        "endFreq": 2620,
        "owner": "Public Safety",
        "ownerLongName": "Public Safety",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 2600,
        "type": "generic"
      }
    ]
  },
  {
    "extraInfo": {
      "description": "Until May 2023 block from 3400 MHz to 3600 MHz blocks are 21 MHz wide, here they are represented as 20 MHz blocks for clarity"
    },
    "names": [
      "n78"
    ],
    "spectrumData": [
      {
        "endFreq": 3500,
        "owner": "FWA",
        "ownerLongName": "FWA",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3440,
        "type": "generic"
      },
      {
        "endFreq": 3540,
        "owner": "Public Safety",
        "ownerLongName": "Public Safety",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3500,
        "type": "generic"
      },
      {
        "details": [
          "In Valle d'Aosta and Provincia Autonoma di Bolzano this block is from 3460 MHz to 3480 MHz"
        ],
        "endFreq": 3560,
        "nrarfcns": [
          636768
        ],
        "owner": "Tim",
        "ownerLongName": "Tim",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3540,
        "type": "tdd"
      },
      {
        "details": [
          "In Valle d'Aosta and Provincia Autonoma di Bolzano this block is divided into two block: one of 40 MHz (NRARFCN 636480 and 636576) and one of 20 MHz (NRARFCN 640320 and 640704)"
        ],
        "endFreq": 3620,
        "nrarfcns": [
          638016
        ],
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3560,
        "type": "tdd"
      },
      {
        "endFreq": 3640,
        "nrarfcns": [
          641664
        ],
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3620,
        "type": "tdd"
      },
      {
        "endFreq": 3720,
        "nrarfcns": [
          643296,
          645312
        ],
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3640,
        "type": "tdd"
      },
      {
        "endFreq": 3800,
        "nrarfcns": [
          648768,
          650688
        ],
        "owner": "Tim",
        "ownerLongName": "Tim",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 3720,
        "type": "tdd"
      }
    ]
  },
  {
    "names": [
      "n257"
    ],
    "spectrumData": [
      {
        "endFreq": 26700,
        "owner": "WindTre",
        "ownerLongName": "WindTre",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 26500,
        "type": "tdd"
      },
      {
        "endFreq": 26900,
        "owner": "Iliad",
        "ownerLongName": "Iliad",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 26700,
        "type": "tdd"
      },
      {
        "endFreq": 27100,
        "owner": "Tim",
        "ownerLongName": "Tim",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 26900,
        "type": "tdd"
      },
      {
        "endFreq": 27300,
        "owner": "Fastweb",
        "ownerLongName": "Fastweb",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 27100,
        "type": "tdd"
      },
      {
        "endFreq": 27500,
        "owner": "Vodafone",
        "ownerLongName": "Vodafone",
        "sourceInfo": {
          "type": "url",
          "url": "https://lteitaly.it/it/spectrum.php"
        },
        "startFreq": 27300,
        "type": "tdd"
      }
    ]
  }
]

### Any additional comments?

GitHub wouldn't let me attach JSON file. Colors for operators are: #1D19A3 for Tim, #FD0000 for Vodafone, #D40000 for Iliad, #FF5700 for WindTre and #FFC600 for Fastweb

**Comment by MattiaFenzi** [comment]
[spectrum-data.json.txt](https://github.com/davwheat/mobile-spectrum-data/files/11455503/spectrum-data.json.txt)
Updated WindTre B1

**Comment by davwheat** [comment]
Thanks. I'll try and get this live this week.
