### ISSUE TITLE
Editing spectrum data for EE 4G Band 28, O2 5G Band 78

### ISSUE THREAD

**Issue by ExperiencersInternational** [davwheat/mobile-spectrum-data#48]
### Country two-letter code

GB

### JSON spectrum data file

[spectrum-data.json](https://github.com/user-attachments/files/15806534/spectrum-data.json)

Hoping this should work fine, the spectrum editor isn't easy to use on mobile

### What has changed?

- [ ] Metadata (country name, extra info, country code, etc)
- [ ] LTE Band 1
- [ ] LTE Band 2
- [ ] LTE Band 3
- [ ] LTE Band 4
- [ ] LTE Band 5
- [ ] LTE Band 7
- [ ] LTE Band 8
- [ ] LTE Band 11
- [ ] LTE Band 12
- [ ] LTE Band 13
- [ ] LTE Band 14
- [ ] LTE Band 17
- [ ] LTE Band 18
- [ ] LTE Band 19
- [ ] LTE Band 20
- [ ] LTE Band 21
- [ ] LTE Band 24
- [ ] LTE Band 25
- [ ] LTE Band 26
- [X] LTE Band 28
- [ ] LTE Band 29
- [ ] LTE Band 30
- [ ] LTE Band 31
- [ ] LTE Band 32
- [ ] LTE Band 34
- [ ] LTE Band 37
- [ ] LTE Band 38
- [ ] LTE Band 39
- [ ] LTE Band 40
- [ ] LTE Band 41
- [ ] LTE Band 42
- [ ] LTE Band 43
- [ ] LTE Band 46
- [ ] LTE Band 47
- [ ] LTE Band 48
- [ ] LTE Band 50
- [ ] LTE Band 51
- [ ] LTE Band 53
- [ ] LTE Band 65
- [ ] LTE Band 66
- [ ] LTE Band 67
- [ ] LTE Band 69
- [ ] LTE Band 70
- [ ] LTE Band 71
- [ ] LTE Band 72
- [ ] LTE Band 73
- [ ] LTE Band 74
- [ ] LTE Band 75
- [ ] LTE Band 76
- [ ] LTE Band 85
- [ ] LTE Band 87
- [ ] LTE Band 88
- [ ] LTE Band 103
- [ ] NR Band n1
- [ ] NR Band n2
- [ ] NR Band n3
- [ ] NR Band n5
- [ ] NR Band n7
- [ ] NR Band n8
- [ ] NR Band n12
- [ ] NR Band n13
- [ ] NR Band n14
- [ ] NR Band n18
- [ ] NR Band n20
- [ ] NR Band n24
- [ ] NR Band n25
- [ ] NR Band n26
- [ ] NR Band n28
- [ ] NR Band n29
- [ ] NR Band n30
- [ ] NR Band n34
- [ ] NR Band n38
- [ ] NR Band n39
- [ ] NR Band n40
- [ ] NR Band n41
- [ ] NR Band n46
- [ ] NR Band n47
- [ ] NR Band n48
- [ ] NR Band n50
- [ ] NR Band n51
- [ ] NR Band n53
- [ ] NR Band n65
- [ ] NR Band n66
- [ ] NR Band n67
- [ ] NR Band n70
- [ ] NR Band n71
- [ ] NR Band n74
- [ ] NR Band n75
- [ ] NR Band n76
- [ ] NR Band n77
- [X] NR Band n78
- [ ] NR Band n79
- [ ] NR Band n80
- [ ] NR Band n81
- [ ] NR Band n82
- [ ] NR Band n83
- [ ] NR Band n84
- [ ] NR Band n85
- [ ] NR Band n86
- [ ] NR Band n89
- [ ] NR Band n90
- [ ] NR Band n91
- [ ] NR Band n92
- [ ] NR Band n93
- [ ] NR Band n94
- [ ] NR Band n95
- [ ] NR Band n96
- [ ] NR Band n97
- [ ] NR Band n98
- [ ] NR Band n99
- [ ] NR Band n100
- [ ] NR Band n101
- [ ] NR Band n102
- [ ] NR Band n104
- [ ] Anything else (explain below)

### Any additional comments?

O2 n78 650976: https://www.ispreview.co.uk/talk/threads/o2-speed-tests.41577/post-368014

EE B28 9460 (used very rarely by the sounds of it, one deployment is for coverage reasons pending installation of a new mast): https://www.ispreview.co.uk/talk/threads/ee-mvno-related-posts.40931/post-368875

**Comment by ExperiencersInternational** [comment]
Can't be bothered to update the JSON but I've also seen a 40MHz deployment in their lower block in outer London

Not in the area now since I don't live in the area so you'll have to take my word for it (about 2 hours away)

![Screenshot_20240622-224300](https://github.com/davwheat/mobile-spectrum-data/assets/56035537/c1529139-e004-4317-9fc8-e1cc2bfdb909)

**Comment by ExperiencersInternational** [comment]
> Can't be bothered to update the JSON but I've also seen a 40MHz deployment in their lower block in outer London
> 
> Not in the area now since I don't live in the area so you'll have to take my word for it (about 2 hours away)
> 
> ![Screenshot_20240622-224300](https://private-user-images.githubusercontent.com/56035537/341998748-c1529139-e004-4317-9fc8-e1cc2bfdb909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNzQ2OTYsIm5iZiI6MTcxOTE3NDM5NiwicGF0aCI6Ii81NjAzNTUzNy8zNDE5OTg3NDgtYzE1MjkxMzktZTAwNC00MzE3LTlmYzgtZTFjYzJiZmRiOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDIwMjYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MjJmZGQ5ZTAxZDMyMGU4YzgwMWVmM2RhMjc5YTc4ZDgyOTc3YWE2MTk2MGIzODlhYjAwOWVjM2RjZmJiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fTb0rkWQB_azIDRGbIv10eIbvsaWPU7Rsz3hSaGHFVQ)

Just to confirm, someone has also just posted an example of the same block, the exact point is around 3770MHz so it's clearly the upper 40MHz block (suspect spectrum swap has not occurred).

https://www.ispreview.co.uk/talk/threads/o2-speed-tests.41577/post-371124

**Comment by davwheat** [comment]
> so it's clearly the upper 40MHz block (suspect spectrum swap has not occurred).

It's likely prep with radios that support post-swap spectrum but prior to the swap occurring in that area. Rare to see such smarts from Telefónica UK.

**Comment by davwheat** [comment]
The 10MHz n78 is likely bad bandwidth data from the Band 1 LTE being applied onto the n78 carrier by Netmonster.

**Comment by ExperiencersInternational** [comment]
> The 10MHz n78 is likely bad bandwidth data from the Band 1 LTE being applied onto the n78 carrier by Netmonster.

Yeah possibly, should have noticed it honestly. I do recall seeing someone else seeing a 10MHz deployment in the Lake District too.

O2 has been doing some odd stuff though, I have a 5MHz EARFCN 199 deployment near me that was recently added to the last site and I've had it show up on 2 sectors and it looks like other people have too on Cellmapper
