### ISSUE TITLE
Editing spectrum data for Three UK (700Mhz DSS)

### ISSUE THREAD

**Issue by cg0** [davwheat/mobile-spectrum-data#5]
### Country two-letter code

GB

### JSON spectrum data file

```json
[
  {
    "names": [
      "B28",
      "N28"
    ],
    "spectrumData": [
      {
        "details": [
          "Limited LTE use, primarily in central London",
          "Mainly being used for new suburban 5G NR deployments"
        ],
        "earfcns": [
          9260
        ],
        "endFreq": 768,
        "nrarfcns": [
          152210,
          152690
        ],
        "owner": "O2",
        "pairedWith": {
          "endFreq": 713,
          "startFreq": 703,
          "type": "fddUp"
        },
        "startFreq": 758,
        "type": "fddDown"
      },
      {
        "earfcns": [
          9360
        ],
        "endFreq": 778,
        "nrarfcns": [
          154570
        ],
        "owner": "Three",
        "pairedWith": {
          "endFreq": 723,
          "startFreq": 713,
          "type": "fddUp"
        },
        "startFreq": 768,
        "type": "fddDown"
      },
      {
        "endFreq": 788,
        "nrarfcns": [
          156510
        ],
        "owner": "EE",
        "pairedWith": {
          "endFreq": 733,
          "startFreq": 723,
          "type": "fddUp"
        },
        "startFreq": 778,
        "type": "fddDown"
      }
    ]
  }
]
```

### What has changed?

- [ ] Metadata (country name, extra info, country code, etc)
- [ ] LTE Band 1
- [ ] LTE Band 2
- [ ] LTE Band 3
- [ ] LTE Band 4
- [ ] LTE Band 5
- [ ] LTE Band 7
- [ ] LTE Band 8
- [ ] LTE Band 11
- [ ] LTE Band 12
- [ ] LTE Band 13
- [ ] LTE Band 14
- [ ] LTE Band 17
- [ ] LTE Band 18
- [ ] LTE Band 19
- [ ] LTE Band 20
- [ ] LTE Band 21
- [ ] LTE Band 24
- [ ] LTE Band 25
- [ ] LTE Band 26
- [X] LTE Band 28
- [ ] LTE Band 29
- [ ] LTE Band 30
- [ ] LTE Band 31
- [ ] LTE Band 32
- [ ] LTE Band 34
- [ ] LTE Band 37
- [ ] LTE Band 38
- [ ] LTE Band 39
- [ ] LTE Band 40
- [ ] LTE Band 41
- [ ] LTE Band 42
- [ ] LTE Band 43
- [ ] LTE Band 46
- [ ] LTE Band 47
- [ ] LTE Band 48
- [ ] LTE Band 50
- [ ] LTE Band 51
- [ ] LTE Band 53
- [ ] LTE Band 65
- [ ] LTE Band 66
- [ ] LTE Band 67
- [ ] LTE Band 69
- [ ] LTE Band 70
- [ ] LTE Band 71
- [ ] LTE Band 72
- [ ] LTE Band 73
- [ ] LTE Band 74
- [ ] LTE Band 75
- [ ] LTE Band 76
- [ ] LTE Band 85
- [ ] LTE Band 87
- [ ] LTE Band 88
- [ ] LTE Band 103
- [ ] NR Band n1
- [ ] NR Band n2
- [ ] NR Band n3
- [ ] NR Band n5
- [ ] NR Band n7
- [ ] NR Band n8
- [ ] NR Band n12
- [ ] NR Band n13
- [ ] NR Band n14
- [ ] NR Band n18
- [ ] NR Band n20
- [ ] NR Band n24
- [ ] NR Band n25
- [ ] NR Band n26
- [X] NR Band n28
- [ ] NR Band n29
- [ ] NR Band n30
- [ ] NR Band n34
- [ ] NR Band n38
- [ ] NR Band n39
- [ ] NR Band n40
- [ ] NR Band n41
- [ ] NR Band n46
- [ ] NR Band n47
- [ ] NR Band n48
- [ ] NR Band n50
- [ ] NR Band n51
- [ ] NR Band n53
- [ ] NR Band n65
- [ ] NR Band n66
- [ ] NR Band n67
- [ ] NR Band n70
- [ ] NR Band n71
- [ ] NR Band n74
- [ ] NR Band n75
- [ ] NR Band n76
- [ ] NR Band n77
- [ ] NR Band n78
- [ ] NR Band n79
- [ ] NR Band n80
- [ ] NR Band n81
- [ ] NR Band n82
- [ ] NR Band n83
- [ ] NR Band n84
- [ ] NR Band n85
- [ ] NR Band n86
- [ ] NR Band n89
- [ ] NR Band n90
- [ ] NR Band n91
- [ ] NR Band n92
- [ ] NR Band n93
- [ ] NR Band n94
- [ ] NR Band n95
- [ ] NR Band n96
- [ ] NR Band n97
- [ ] NR Band n98
- [ ] NR Band n99
- [ ] NR Band n100
- [ ] NR Band n101
- [ ] NR Band n102
- [ ] NR Band n104
- [ ] Anything else (explain below)

### Any additional comments?

Sourced from https://twitter.com/PedroClarke1/status/1585177003468066817/

Using the tool was difficult as the import process didn't work for me so I injected the existing array from source into the local storage to work on, would be nice to be able to work off an existing preset.

**Comment by davwheat** [comment]
Hi @cg0!

Thanks for contributing this. I have implemented your changes. They should pop up on https://mastdatabase.co.uk later today.

Cheers!
